version: "3.8"

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs

  gara1:
    build: ./app_gara1
    container_name: gympoints_gara1
    restart: always
    ports:
      - "8501:8501"

  gara2:
    build: ./app_gara2
    container_name: gympoints_gara2
    restart: always
    ports:
      - "8502:8501"
