
services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - gympoints-net

  gara1:
    build: ./app_gara1
    container_name: gara1
    restart: always
    networks:
      - gympoints-net


networks:
  gympoints-net:
    driver: bridge
